services:
  - type: web
    name: label-in-a-box
    env: python
    buildCommand: cd frontend && npm install && npm run build && cd .. && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    autoDeploy: true
